# Generated by Django 3.1.2 on 2021-07-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friends_requests',
            new_name='friend_requests',
        ),
    ]
